CREATE TABLE EMPLOYEE (
   ID INTEGER NOT NULL,
   FIRST_NAME VARCHAR(255) NOT NULL,
   LAST_NAME VARCHAR(255) NOT NULL,
   POSITION VARCHAR(255),
   OFFICE VARCHAR(255),
   AGE INTEGER,
   START_DATE DATE,
   SALARY DECIMAL,
   PRIMARY KEY (ID)
);
